from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.orm import Session
from datetime import datetime, timezone
from typing import Dict, Any, List
from ..database import get_db
from ..models.entities import Investigation, Entity, Evidence, Relationship, TimelineEvent
from ..schemas.schemas import InvestigationReportSchema

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("/generate/{case_id}", response_model=InvestigationReportSchema)
def generate_investigation_report(case_id: str, db: Session = Depends(get_db)):
    inv = db.query(Investigation).filter(Investigation.case_id == case_id).first()
    if not inv:
        # If no custom case, generate report for default demo target
        target_name = "Packrat & Associated Infrastructure"
        analyst_name = "Lead Threat Intelligence Analyst"
    else:
        target_name = inv.target_entity or inv.name
        analyst_name = inv.analyst

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Gather observed digital indicators
    cti_ev = db.query(Evidence).filter(Evidence.source == "CTI").limit(15).all()
    bc_ev = db.query(Evidence).filter(Evidence.source == "BLOCKCHAIN").limit(10).all()
    dw_ev = db.query(Evidence).filter(Evidence.source == "DARKWEB").limit(10).all()
    pgp_ev = db.query(Evidence).filter(Evidence.source == "PGP").all()
    all_rels = db.query(Relationship).order_by(Relationship.confidence_score.desc()).limit(20).all()

    observed_ids = [
        {"type": ev.entity_type, "value": ev.entity_value, "source": ev.source, "evidence_id": ev.evidence_id}
        for ev in (cti_ev[:5] + bc_ev[:3] + pgp_ev)
    ]

    blockchain_findings = [
        {"entity": ev.entity_value, "role": ev.context, "evidence_id": ev.evidence_id}
        for ev in bc_ev[:5]
    ]

    cti_findings = [
        {"indicator": ev.entity_value, "type": ev.entity_type, "provenance": ev.provenance, "evidence_id": ev.evidence_id}
        for ev in cti_ev[:8]
    ]

    darkweb_findings = [
        {"thread_reference": ev.entity_value, "anonymity_status": "Author anonymized in source dataset", "evidence_id": ev.evidence_id}
        for ev in dw_ev[:5]
    ]

    pgp_findings = [
        {"fingerprint": ev.entity_value, "role": "Reference digital signature (CIRCL)", "evidence_id": ev.evidence_id}
        for ev in pgp_ev
    ]

    correlation_findings = [
        {
            "relationship_id": rel.relationship_id,
            "type": rel.relationship_type,
            "confidence_score": rel.confidence_score,
            "explanation": rel.explanation
        }
        for rel in all_rels[:10]
    ]

    supporting_ev_ids = [ev.evidence_id for ev in (cti_ev[:8] + bc_ev[:5] + pgp_ev)]

    uncertainties = [
        "Dark web forum authors are masked/anonymized in the research corpus ([AUTHOR]); cannot attribute authorship to physical persons.",
        "Public blockchain wallet transactions prove digital asset flow, but do not provide legal identity attribution without subpoena/KYC records.",
        "PGP keys represent cryptographic identifiers and verified UIDs; CIRCL key is a test/reference entity and not an adversary.",
        "All correlations represent multi-source digital indicator clustering, NOT verified civilian real-world identity."
    ]

    return InvestigationReportSchema(
        case_id=case_id,
        title=f"Forensic Threat Intelligence Assessment: {target_name}",
        generated_at=now_str,
        analyst=analyst_name,
        primary_target=target_name,
        executive_summary=(
            f"TRACE-X investigated digital indicators associated with '{target_name}'. "
            "Correlated multi-source telemetry spanning CIRCL MISP OSINT C2 infrastructure, "
            "public Ethereum ledger transactions, and DarkForums database leak threads. "
            "Evidence clustering confirms strong digital association between campaign hostnames, "
            "IP infrastructure, and payload hashes. Insufficient authorized KYC/legal evidence exists "
            "for physical real-world person attribution."
        ),
        observed_identifiers=observed_ids,
        blockchain_findings=blockchain_findings,
        cti_findings=cti_findings,
        darkweb_findings=darkweb_findings,
        pgp_findings=pgp_findings,
        correlation_findings=correlation_findings,
        supporting_evidence_ids=supporting_ev_ids,
        uncertainties_and_limitations=uncertainties,
        attribution_verdict="INSUFFICIENT AUTHORIZED EVIDENCE FOR REAL-WORLD PERSON ATTRIBUTION (Strong Digital Infrastructure Correlation Confirmed)",
        analyst_signature=f"Digitally Generated by TRACE-X Engine // Analyst: {analyst_name}"
    )
